#!/bin/bash

# Script to run all unit tests for code in any directory in the entirety of the known universe
# and (somehow) beyond.
 
# This test script will extend the boundaries of human knowledge.

# It is all-knowing. It may share some.

node ../../node_modules/jasmine/bin/jasmine.js --config=jasmine.json

# Nice thing to have in the future would be a test script
# where we can include the name of a module as a param
# and only run those unit tests